### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by yongleex** [ztangent/multimodal-dmm#2]
I use the latest pytorch with version 1.2.0, and find out the follow syntax (about 5 places occured) is not supported anymore.  And you adopt unit8 as the dtype of a mask.
>             mask_m = 1 - torch.isnan(inputs[m]).flatten(2,-1).any(dim=-1)
I have fixed it in my PC. Can you change the mask with a bool type for a better reproducing?
>            mask_m = ~ torch.isnan(inputs[m]).flatten(2,-1).any(dim=-1)

Thanks

**Comment by ztangent** [comment]
I recommend using torch 1.1.0 for now, because this is a breaking change in torch 1.2.0. I've updated the README to make clear that torch 1.1.0 should be installed.

**Comment by yongleex** [comment]
It's ok, thanks.
