### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by yongleex** [ztangent/multimodal-dmm#4]
Quotients of Gaussian Distribution may not correctly implemented.
You use following 
>dmm.py->forward()->#smooth pass-> inv_std = -inv_std. 
But your function <product_of_experts()> cann't perform  correctly.

Thanks.

**Comment by ztangent** [comment]
Thanks for catching this! I've fixed the issue in 5a965d and redid some of the experiments -- it (surprisingly?) doesn't appear to affect performance / accuracy significantly.
